project:
  type: website
  output-dir: docs

website:
  title: "Workshop Name"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Outline
  sidebar: 
      style: docked
      contents:
        - href: materials/slides/introduction.qmd
          text: "Introduction slides"
        - href: materials/activity/01-activity1/activity1.qmd
          text: "Activity 1"
format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

